### ISSUE TITLE
[FIX] 여행 생성 디테일 수정

### ISSUE THREAD

**Issue by Limgabi** [dnd-side-project/dnd-9th-8-frontend#108]
## 📌 Issue
여행 생성 디테일 수정

## ✅ Todo
- [ ] 인원 선택 바텀시트 최소 인원 수정
- [ ] 인원 선택 바텀시트 버튼 비활성화 색 반영
- [ ] 여행 정보 확인 페이지 여럿이/혼자서 라이팅 반영
